apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-devops-app
  labels:
    app: my-devops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-devops-app
  template:
    metadata:
      labels:
        app: my-devops-app
    spec:
      containers:
        - name: my-devops-app
          image: my-devops-app
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: my-devops-app-config
            - secretRef:
                name: my-devops-app-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"